### ISSUE TITLE
USB webcams and mics fail since 5.10.x update

### ISSUE THREAD

**Issue by nachokb** [flathub/us.zoom.Zoom#334] opened 2022-05-27 14:13 UTC
Ever since the upgrade to 5.10.x I can't use any USB mic or webcam. Downgrading to 5.9.6 makes everything work again.

This happens on wayland and xorg sessions, on Ubuntu 22.04.

The devices get listed in the dropdown but when chosen, no audio is heard for the mic and a black stream is sent for the cam.

By chance I tried the built-in mic and realized it only happens with USB devices.

**Comment by smlx** [comment] 2022-05-30 11:26
I've got a USB webcam and microphone working with version `5.10.6.3192`. Maybe something else is going on with your USB hub? Anything in `dmesg`?

**Comment by dtrunk90** [comment] 2022-06-01 08:07
Same for my usb webcam on 20.04.4 LTS
USB mic is working but webcam isn't.
With "cheese"/outside of flatpak the webcam is working.
Version: 5.10.6 (3192)

**Comment by nachokb** [comment] 2022-06-01 13:30
(still testing)

**Comment by nachokb** [comment] 2022-06-02 14:04
ok if I run zoom via `flatpak run` and then join a meeting, I can use my webcam... if I click on a link, then webcam shows a black picture

(still testing)

**Comment by tzie0062** [comment] 2022-06-02 15:14
Same here on `Ubuntu 20.04` and a `Logitech, Inc. Webcam C270`

**Comment by nachokb** [comment] 2022-06-10 12:34
similar thing happens to me, but running with `flatpak run us.zoom.Zoom` and joining rooms by number, everything works ok :thinking:

**Comment by makeworld-the-better-one** [comment] 2022-06-14 13:19
@nachokb I can confirm that my camera only works when joining rooms through the Zoom UI. If I join rooms by clicking a link (which is the same as running Zoom from the CLI with a `zoommtg://` URL as argument), then my camera doesn't work.

Importantly, this is not a flatpak-specific issue. The same thing happens with Zoom in a firejail. Maybe with un-sandboxed Zoom as well? Not sure.

**Comment by makeworld-the-better-one** [comment] 2022-06-14 13:20
@tzie0062 thanks for that downgrade fix, that works for me as well.

**Comment by dtrunk90** [comment] 2022-06-15 13:10
It started happening again. Mic works always but Webcam doesn't. Nevermind. Downgrading to 5.9.6 with your above provided command and everything seems to work again. Maybe I should try the official deb if the error occurs there as well. Or maybe I should get rid of flatpak at all because it only brings weird issues I don't want to get bothered with.

**Comment by jbiel** [comment] 2022-06-15 22:16
> Or maybe I should get rid of flatpak at all because it only brings weird issues I don't want to get bothered with.

FWIW I've had the opposite experience on Arch (the Flatpak has been much more stable than the [AUR pkg](https://aur.archlinux.org/packages/zoom).) The comments on the AUR have a lot of traffic and seem to be a lot of the same issues as what's reported here. I wish Zoom would improve their development team.

**Comment by ledufakademy** [comment] 2022-06-21 12:35
same issue here on ubuntu 20.04 LTS, last release : video issue, camera is working 2 sec. then freeze. (zoom still working)

**Comment by dtrunk90** [comment] 2022-06-24 11:22
Seems to be fixed with 5.11 now

**Comment by makeworld-the-better-one** [comment] 2022-06-25 16:48
Can confirm, this issue is fixed for me.

```
sudo flatpak mask --remove us.zoom.Zoom
flatpak upgrade
```

**Closed** 2022-06-29 08:59 UTC
