### ISSUE TITLE
KDE/Wayland - Zoom v6.x cannot share individual windows

### ISSUE THREAD

**Issue by MirandaStreeter** [flathub/us.zoom.Zoom#477] opened 2024-08-21 21:10 UTC
When clicking the "Share" button at the bottom during a zoom meeting, only the following shows:

![image](https://github.com/user-attachments/assets/a898d0b2-0352-45a2-996f-b640214f4055)

And the following appears in the journal:

```
Aug 21 13:06:26 <hostname> kwin_wayland[1083]: kf.windowsystem: static bool KX11Extras::mapViewport() may only be used on X11
```

If I click "Use system window capture" and click "Share", instead of the normal portal selection for windows I get the following popup:
![image](https://github.com/user-attachments/assets/82707c70-327f-48e2-8a04-c5a6a369719f)

This is a permissions popup from the `xdg-desktop-portal-kde` backend. If I click "share" I don't get to pick any window, but instead my entire desktop spanning all monitors is shared, and the "Remote Desktop" tray icon is made available: 
![image](https://github.com/user-attachments/assets/bf815d0b-121c-4d3e-86b1-c5b06bedcf0a)

If I were to get a popup I would expect to instead be presented with a selection of screens/windows via the portal to pick from, like so:
![image](https://github.com/user-attachments/assets/f2882b34-9c46-462e-a605-869332bbead4)

The above is an example using a different screen sharing application running via flatpak, meaning the issue is likely not an issue with KDE itself.

More details:
- There are no other relevant logs in the journal I can see
- My `zoomus.conf` file's `enableWaylandShare=true` is set
- Under Settings > Share Screen > Advanced I have "Screen capture mode on Wayland" set to "Pipewire Mode"
- This used to work under Zoom v5.x
- The same issue occurs with or without the KDE "XWayland Video Bridge" service running
- The same issue occurs regardless whether the `zoomus.conf` file's `xwayland=true` parameter is flipped to `false`
- Setting the `XDG_CURRENT_DESKTOP` environment variable to `gnome` does not make a difference:
```
$ cat ~/.local/share/flatpak/overrides/us.zoom.Zoom 
[Environment]
XDG_CURRENT_DESKTOP=gnome
```
- Despite the "Remote control requested" popup, this doesn't look or act like a real remote control session. The same behavior also happens whether or not the setting is enabled:
![image](https://github.com/user-attachments/assets/0bc0f2bf-db73-419e-9554-700951934b7f)
- I've been able to reproduce this on both Fedora KDE 40 and latest Arch as of 2024-08-21

***

To reiterate in case it isn't clear, this is sharing all my desktops at once no matter what I select! For my dual 4k display setup this is quite unusable for any viewer.

I'd love if someone else could verify this happens to them on KDE Wayland w/ Zoom v6.x and confirm this isn't some odd issue with my account settings.

**Comment by qu-jieniu** [comment] 2024-08-22 16:11
Same! I tried installing the latest rpm from zoom.us but also having the same issue, so the issue might not be related to flatpak.  I do recall there's a working version.

**Comment by sannagy90** [comment] 2024-08-28 20:43
Screen sharing is completely non-functional on sway and I think this issue could have the same rootcause as they broke in the same update. if I were to guess zoom is relying on something that only gnome implements, just like they used gnome specific implementation for screen sharing on wayland before they moved to xdg-desktop-portal backend.

The irony is that zoom is completely unusable on gnome as well if you are using virtual desktops. Once your meeting is minimized you cannot maximize the window again and you are forced to reconnect...

**Comment by sannagy90** [comment] 2024-08-30 23:39
> > Screen sharing is completely non-functional on sway and I think this issue could have the same rootcause as they broke in the same update. if I were to guess zoom is relying on something that only gnome implements, just like they used gnome specific implementation for screen sharing on wayland before they moved to xdg-desktop-portal backend.
> 
> for me it seems like that it is failing right after trying to use the `org.freedesktop.portal.RemoteDesktop` protocol that is so far not implemented in xdpw/xdph and zoom being zoom it is not handled very gracefully (6.1.11, hyprland)
> 
> I know its the kde thread, to not be completely off-topic: it might help to debug to check the dbus conversation while sharing

Zoom indeed is trying to query for  org.freedesktop.portal.RemoteDesktop. I tested with a fork of xdg-desktop-portal-wlr which implements RemoteDesktop and I was able to pick the output to be shared, but Zoom completely crashes right after I select the output. I guess we will have to wait until this is implemented on wlr based wms and hope that it will actually work.

**Comment by takluyver** [comment] 2024-09-19 09:43
I have no reason to think this will be fixed, but does anyone on KDE want to test the Zoom 6.2 update, which is prepared in PR #481?

**Comment by paidhi** [comment] 2024-09-23 08:52
I see the same issue with the official RPM from the Zoom website on Fedora 40 (6.2.0-1855).

**Comment by w10have** [comment] 2024-09-25 14:28
I was a very happy Linux zoom'er under Fedora 40 prior till moment my workstation was updated to plasma-workspace-wayland-6.1.5... I do not remember which version I was on exactly, I figure 6.0.xyz and everything was working like a charme.

Now with latest I see exactly this problem too.  And it frustrates me to the max.

I understand that my comment doesn't contribute to the problem, I only hope a fix is made asap.

zoom-6.1.11.1545-1.x86_64

**Comment by yakovpol** [comment] 2024-10-04 08:45
The only working solution I have found so far is downgrade. Zoom version 6.0.12 (5501) works as it should

**Comment by takluyver** [comment] 2024-10-04 09:24
I have seen people on the Zoom forums complaining about a similar sounding issue when you end screen sharing, and saying it's an incompatibility with a newer version of Pipewire (1.2?).

**Comment by JeffreyAnimal** [comment] 2024-10-25 16:42
> > If it's not a flatpak issue then I'm quite confused. It sounds like it works fine on Gnome, but it should all be using the same protocols and pipewire captures. Is there someone on the latest LTS KDE (v5.27.x) that can try out Zoom v6.x and verify whether it works or not?
> > If it works on an older KDE then there's something to bug them about.
> > If it still doesn't work and the issue is upstream then I'm curious if there's something hardcoded that we can work around with a bit of a hack ala #474
> 
> I can confirm that on Debian sid and KDE Plasma 5, the latest zoom 6.1 has the exact issue described here.
> 
> The only way I was able to regain support for individual window share was by downgrading to 6.0.X with the following flatpak command, you're welcome to reference the commit if desired. `sudo flatpak update --commit=b9505f108b5f9acb2bbad83ac66f97b42bc6a75b9c28ed7b75dec1040e013305 us.zoom.Zoom`

I can confirm downgrading to 6.0.x works.

For downgrading Zoom on Debian I did the following:

1. Searched on the [Releases-Page](https://support.zoom.com/hc/en/category?id=kb_category&kb_category=625afeda8720391089a37408dabb3596) for the Workspace-App and selected a available Version  (in my case: 6.0.12 (5501)).
1. Edited the Download-Link of the `.deb` Package to the selected Version `6.x.y.abc`: <https://zoom.us/client/6.x.y.abc/zoom_amd64.deb>
1. Downloaded file and  installed the package by the usual `sudo apt install <download-path>/zoom_amd64.deb` command

**Comment by cyrusmallon** [comment] 2024-11-11 16:09
I am having the same problem on ubuntu 22.04 with zoom 6.2.6. $XDG_SESSION_TYPE is wayland.

**Comment by konecny-ondrej** [comment] 2024-11-19 14:18
Zoom 6.2.10 (4983) now has 2 options for screensharing on Wayland:
- Pipewire Mode - allows selecting individual windows to share, but your keyboard/mouse cannot be controlled remotely.
- Pipewire Mode (Remote Control) - always shares entire screen, but allows remote control.

**Comment by muralito** [comment] 2024-11-23 15:47
Zoom 6.2.10 (4983) seems to be working, but needs that the user changes the advanced setting from auto to "Pipewire Mode"...
The default setting of "auto mode" doesn't work.

The problem now is that is somewhat unstable, zoom sometimes crashes a few seconds after joining a meeting.
Some debug data is in .zoom/zoom_stdout_stderr.log that seems to point to TensorFlow...

**Closed as completed** 2024-12-08 02:11 UTC
