### ISSUE TITLE
[Bug] Zoom call doesn't launch through link on the browser after latest update

### ISSUE THREAD

**Issue by hyuri** [flathub/us.zoom.Zoom#326] opened 2022-05-01 18:57 UTC
Hi, after the latest update, Zoom won't launch a call through a Zoom link. It won't even open the app.

Seems to me to have something to do with this --no-sandbox thing.

It's happening in both Chromium and Firefox (.deb/repo version).

My system:
OS: Pop!_OS 21.10
GPU: Intel HD4000 + Nvidia GeForce 630M (using the Nvidia)

**Comment by darrencocco** [comment] 2022-05-02 06:09
Attached is a log from Zoom when it fails (used a tel: uri)
[error_snippet.txt](https://github.com/flathub/us.zoom.Zoom/files/8601093/error_snippet.txt)

**Comment by euclip** [comment] 2022-05-02 06:55
It seems I've been bitten by this as well on Fedora 35 Workstation after the latest update. When I try to sign in through SSO, I immediately get a notification about Zoom crashing.

**Comment by andreasknoben** [comment] 2022-05-02 10:46
Ubuntu 22.04 - Zoom does not launch by any link, whether it is an SSO login link or a meeting link; tested in Firefox and Chromium. I am not sure where I could obtain logs for any relevant information.

**Comment by akosma** [comment] 2022-05-02 11:05
Confirming this on Ubuntu 20.04 as well, not working with Firefox nor Chromium.

**Comment by muelli** [comment] 2022-05-02 12:03
hm.
But does it work with the non-flatpaked version?
If so, I am wondering whether we should revert the update.

**Comment by andreasknoben** [comment] 2022-05-02 14:02
@muelli It does work on the non-Flatpak version (.deb).

**Comment by hbrown-uiowa** [comment] 2022-05-02 14:28
Error messages will be in `~/.xsession-errors` usually. 

This is the error I'm seeing:
```
[0502/090110.788234:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /app/extra/zoom/cef/chrome-sandbox is owned by root and has mode 4755.
No PulseAudio daemon running, or not running as session daemon.
                             Class      App      Lib Possible Culprit Flags
                resip::Connection      648      648 
                      resip::Data       36       36 
                 resip::DnsResult     1080     1080 
                   resip::Headers        1        1 
          resip::MsgHeaderScanner       40       40 
                resip::SipMessage     5208     5208 
         resip::TransportSelector      864      864 
                     resip::Tuple      128      128 
              resip::UdpTransport     1144     1144 
          resip::GenericIPAddress       28       28 

zoom started.
zoom was exited due to a handled signal: 5 
ZoomLauncher exit.

```

I adjusted the permissions on /var/lib/flatpak/app/us.zoom.Zoom/x86_64/stable/5a053c38cffafb9fb95a5f37dd225a7f7a50aa8b1c869a07d1922a61144e7a6c/files/extra/zoom/cef/chrome-sandbox and it didn't fix anything.

**Comment by hyuri** [comment] 2022-05-02 15:37
In my case, it's happening in both Chromium and Firefox (.deb/repo version).

And my system is:
- OS: Pop!_OS 21.10
- GPU: Intel HD4000 + Nvidia GeForce 630M (using the Nvidia)

**Comment by blockloop** [comment] 2022-05-02 16:17
Same problem with me. I don't know if this is specific to the flatpak. I believe it happened with the deb as well. Either way this works for me for now:

```
sudo flatpak update --commit=a4a6a5c0c55a06ed7786276c9758baf7578e30bc1db4dd5d267cbb39d18884d3 us.zoom.Zoom
```

This will downgrade zoom to 

```
    Commit: a4a6a5c0c55a06ed7786276c9758baf7578e30bc1db4dd5d267cbb39d18884d3
   Subject: Update zoom.tar.xz to 5.9.6.2225 (32830a02)
      Date: 2022-02-28 11:58:24 +0000
```

You can get a list of the previous commits with 

```
flatpak remote-info --log flathub us.zoom.Zoom
```

**Comment by joschmitt** [comment] 2022-05-02 19:20
I also have this issue on Debian testing (bookworm). The .deb from the zoom website works for me.

**Comment by liskin** [comment] 2022-05-03 16:02
I think the important bit is this one:

`[0502/090110.788234:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /app/extra/zoom/cef/chrome-sandbox is owned by root and has mode 4755.`

When I launch zoom without any arguments, that error isn't there. Looks like the `--no-sandbox` argument passed by the /app/bin/zoom wrapper only works when no other arguments are present?

**Comment by liskin** [comment] 2022-05-03 20:01
Indeed, upon fixing the sandbox, it works okay again (at least here). PR here: https://github.com/flathub/us.zoom.Zoom/pull/328

**Comment by hyuri** [comment] 2022-05-03 21:12
> Indeed, upon fixing the sandbox, it works okay again (at least here). PR here: #328

If I understand it, this only fixes it for Chromium-based apps, right? After this fix, does the issue persists using Firefox?

**Comment by liskin** [comment] 2022-05-03 22:03
@hyuri Should be all right for Firefox as well. The sandbox I'm talking about is the Electron/Chromium sandbox inside of Zoom, not in the browser which invokes Zoom through xdg-open or whatnot. Perhaps you can give this: https://github.com/flathub/us.zoom.Zoom/pull/328#issuecomment-1116531778 a try?

**Comment by hookenz** [comment] 2022-05-03 22:04
Confirmed, broken in Zorin 16 as well.

**Comment by hyuri** [comment] 2022-05-03 22:10
> @hyuri Should be all right for Firefox as well. The sandbox I'm talking about is the Electron/Chromium sandbox inside of Zoom, not in the browser which invokes Zoom through xdg-open or whatnot. Perhaps you can give this: [#328 (comment)](https://github.com/flathub/us.zoom.Zoom/pull/328#issuecomment-1116531778) a try?

Got it. Thanks for clarifying!

**Closed** 2022-05-04 08:00 UTC
