### ISSUE TITLE
Zoom minimizes and cannot be maximized when switching windows (Wayland + Gnome)

### ISSUE THREAD

**Issue by pchest** [flathub/us.zoom.Zoom#464] opened 2024-06-25 23:41 UTC
When I switch workspaces on Gnome, Zoom minimizes into a small window, as expected. However, when I attempt to restore it to its full size, it oftentimes does not do so. It stays minimized for the whole call unless I close Zoom and rejoin the room. If I click the maximize button repeatedly, the minimized window disappears entirely, leaving me with no way to interact with the room. That said, other members of the room can still see and hear me, even though I cannot see them.

My computer is a Dell Latitude 7320 and my operating system is Fedora 40

**Comment by nedrichards** [comment] 2024-07-26 17:29
This isn't officially supported by zoom so I'd encourage you to report any issues to zoom, although they may ask to you reproduce it directly on their version. This issue may or may not be resolved by https://github.com/flathub/us.zoom.Zoom/pull/470 but since I don't think we can do anything directly ourselves here I'm going to close this.

**Closed by nedrichards** 2024-07-26 17:29 UTC
