### ISSUE TITLE
Zoom SSO login no longer works after update

### ISSUE THREAD

**Issue by Notsonoble** [flathub/us.zoom.Zoom#446] opened 2024-01-30 18:17 UTC
**Expected behavior**

Zoom restarts, login to zoom offers username and password, or the SSO button below.

Click the SSO button. Zoom asks for my domain.zoom.us

Web browser opens asking for my SSO credentials from my institution.

Zoom client logs me in.

**What happens**

All of the above except the last step, zoom doesn't log in, the launch zoom button in the browser does nothing.

**Other notes**

This started after an update that I honestly am not sure if was triggered this week, or had been sitting for a bit and I only noticed this week. It is however a recent-ish change, as before the update (ie last week) zoom could login with no issue.

Additionally, removing the flatpak package and installing the .deb package from zoom.us fixed this issue for me. So it's something with the package, or the package and my combination.

**System Setup**

This happened on two devices.

One running Kubuntu-22.04 LTS
Default browser: Firefox from the PPA (deb pkg not snap)

One running Kubuntu 22.10.
Default browser: Firefox from the PPA (deb pkg not snap)

The 22.10 device i haven't tried the deb package yet (its my home machine, i came into office today).

If you need more info (any flatseal settings, or logs) please reply and I'll attempt to provide.

**Comment by jrstryker** [comment] 2024-01-30 22:22
I am having this exact same problem on Pop!_OS 22.04 LTS (64-bit), Gnome 42.9, X11 windowing system. The browser is Firefox 121.0.1 (64-bit). I believe the Zoom version is 5.17.1.1840.

**Comment by jrstryker** [comment] 2024-01-30 22:39
In my case, installing the .deb (for Ubuntu 18.04+) did not help and the problem seems to remain identical. I have also tried using Chrome instead of Firefox for the authentication and that hasn't helped either.

**Comment by jrstryker** [comment] 2024-01-31 19:35
> In my case, installing the .deb (for Ubuntu 18.04+) did not help and the problem seems to remain identical. I have also tried using Chrome instead of Firefox for the authentication and that hasn't helped either.

Update: The .deb worked for me after trying again today. I believe it helped that this time I deleted "~/.zoom/" between uninstalling the broken Flatpak and installing the official .deb.

**Comment by tommydrum** [comment] 2024-01-31 23:51
This also affected me, but by using the Google SSO option. Deleting .var/app/us.zoom.Zoom (effectively making it a reset), solved the issue.

**Comment by kwyxz** [comment] 2024-02-01 18:46
Having the same issue on RHEL with no chance of installing a native package as several of our users still require running el79 for various reasons and flathub Zoom is our best option.
Reverting the flatpak to commit 04aaf2b043d0887115d5954ca5af88146d48a512021a0770e95b5cff5f7d00e9 is currently our best option.

**Comment by rkaminsk** [comment] 2024-02-07 13:46
I stumbled over the same problem. My current workaround is to downgrade to the previous version:
```sh
flatpak update --commit=04aaf2b043d0887115d5954ca5af88146d48a512021a0770e95b5cff5f7d00e9 us.zoom.Zoom
flatpak mask us.zoom.Zoom
```

**Comment by rwmacleod** [comment] 2024-02-07 21:55
@rkaminsk  Thanks, that works for me!

I didn't take the time to go back and confirm that switching to the HEAD version of us.zoom.Zoom still had the problem.  I have never played with flatpak but it looks like on can switch back to HEAD by quitting Zoom and then running:

flatpak mask --remove us.zoom.Zoom
flatpak update us.zoom.Zoom

Right?

**Comment by x0wllaar** [comment] 2024-02-09 20:27
Are there any logs or something I can provide to help debug this? Downgrading has worked for me, but it's not sustainable in the long run :(

**Comment by kaimast** [comment] 2024-02-11 04:36
> > This also affected me, but by using the Google SSO option. Deleting .var/app/us.zoom.Zoom (effectively making it a reset), solved the issue.
> 
> Thank u, this works, but only for first run of the program. After close and reopen it won't work.

Same here. The fix only works for one start...

**Comment by choffee** [comment] 2024-02-13 10:44
For me exiting zoom, then deleteing both ~/.zoom and ~/.var/app/us.zoom.Zoom the restarting seemed to fix it for me. Now seems to close and start while keeping me logged in.

**Comment by pezz** [comment] 2024-02-14 13:17
Just to be clear to anyone else reading this: deleting the .zoom and .var/app.us.zoom.Zoom dirs doesn't fix this on its own with the latest version, you need to downgrade to the 04aa commit as per @rkaminsk

Mine actually SSOs now so thanks to all for the tips.

**Comment by fmonteghetti** [comment] 2024-02-27 19:28
> I stumbled over the same problem. My current workaround is to downgrade to the previous version:
> 
> ```shell
> flatpak update --commit=04aaf2b043d0887115d5954ca5af88146d48a512021a0770e95b5cff5f7d00e9 us.zoom.Zoom
> flatpak mask us.zoom.Zoom
> ```

This workaround works for me as well, thanks.

**Comment by vwbusguy** [comment] 2024-03-04 19:32
> This also affected me, but by using the Google SSO option. Deleting .var/app/us.zoom.Zoom (effectively making it a reset), solved the issue.

This fixed it for me.  SSO login now works for me with Zoom flatpak and RPM version of Firefox.

**Comment by edenist** [comment] 2024-03-06 00:55
Noting I had to apply this rollback, and joining in to see if this can be fixed as most SSO providers have minimum version requirements which will eventually start kicking in if v5.17.1 gets too out of date.

**Comment by pezz** [comment] 2024-03-06 04:38
FYI.. If you're a user of a single account like me (I only use Zoom for my job), you can revert to the 04aaf commit, perform SSO and login, and Zoom stays logged in. So I'm using the latest flatpak 5.17.5.2543 no worries right now.

**Comment by edenist** [comment] 2024-03-06 06:16
So the actual issue I believe is that zoom won't accept anything passed to it from the browser. This obviously messed up SSO, but I also notice it doesn't open up meeting links either. They have to be entered manually, or be in your integrated calendar.

**Comment by hoshsadiq** [comment] 2024-03-06 18:29
Once you sign in, you can upgrade again. Of course, bear in mind that if you end up getting logged out, you'll have to follow this again until it's fixed.

**Comment by nilehmann** [comment] 2024-03-06 18:50
Note that if you upgrade again, you won't be able to open meeting links from the browser. At least that is what happens to me because not only SSO is broken but everything that requires redirection from the browser.

**Comment by jolars** [comment] 2024-03-12 07:26
In my case, for some reason the flatpak zoom client doesn't add `zoom.us` to the url sent to the browser. Instead it just tries `<company-domain>/<etc>`.

**Comment by dee8een0** [comment] 2024-03-14 16:39
> I stumbled over the same problem. My current workaround is to downgrade to the previous version:
> 
> ```shell
> flatpak update --commit=04aaf2b043d0887115d5954ca5af88146d48a512021a0770e95b5cff5f7d00e9 us.zoom.Zoom
> flatpak mask us.zoom.Zoom
> ```

After downgrade the logon window altered me to upgrade the client. With the latest flatpak version SSO is still not working.

**Comment by 3ernhard** [comment] 2024-03-19 09:33
> Found another workaround that works with the latest flatpak zoom package and the firefox-esr debian package. I haven't tried with the ppa firefox package, the snap package also did not work.
> 
> In firefox got to `about:preferences` under `applications` change the action to `/usr/bin/xdg-open`.

Can confirm that this also work on Firefox 123 rpm on Fedora 39!

**Comment by rkaminsk** [comment] 2024-03-19 10:00
> Found another workaround that works with the latest flatpak zoom package and the firefox-esr debian package. I haven't tried with the ppa firefox package, the snap package also did not work.
> 
> In firefox got to `about:preferences` under `applications` change the action to `/usr/bin/xdg-open`.

I also managed to log in via firefox from the snap. I started zoom manually:
```
flatpak run --command=bash us.zoom.Zoom
zoom
```
For some reason I don't understand I could then just login.

**Comment by brittyazel** [comment] 2024-03-26 20:05
I also have this issue, as well as needing to kill Zoom each time I want to open a Zoom link from the browser. Would love to figure out why this issue is happening.

**Comment by khers** [comment] 2024-03-28 12:38
> flatpak run --command=bash us.zoom.Zoom -i -c zoom

Neither of these solutions work for me (Pop_OS! with firefox from the Pop_OS! repo)

**Comment by sonicnkt** [comment] 2024-04-02 09:11
> > Found another workaround that works with the latest flatpak zoom package and the firefox-esr debian package. I haven't tried with the ppa firefox package, the snap package also did not work.
> > In firefox got to `about:preferences` under `applications` change the action to `/usr/bin/xdg-open`.
> 
> Can confirm that this also work on Firefox 123 rpm on Fedora 39!

Hmm this does not work for me on Fedora 39 with zoom 5.17.11 and firefox 124.0.1 (fedora repo, rpm)

**Comment by siddhpant** [comment] 2024-04-03 16:58
Closed by the above PR.

**Closed** 2024-04-03 19:00 UTC

**Comment by majneb** [comment] 2024-05-13 13:21
I still have the issue with zoom 6.0.2 and firefox 126.0, either with the flatpack or with the deb package.
I tried to manually select the program in /var/lib/flatpack/app... within firefox, or to use xdg-open, with no luck.
My os is the KDE Neon (ubuntu22.04 base) with KDE 6 wayland.

**Comment by travisdowns** [comment] 2024-06-07 19:42
> Fixed by the above PR.

@siddhpant only for flatpak or also for the .deb?

**Comment by travisdowns** [comment] 2024-06-07 19:49
I still have the issue with Zoom 6.0.12 installed from .deb on Ubuntu and Firefox 126.0 installed via snap.

**Comment by siddhpant** [comment] 2024-06-07 19:50
> > Fixed by the above PR.
> 
> @siddhpant only for flatpak or also for the .deb?

@travisdowns Just flatpak as this is the flatpak repo. Native installs don't have this issue.

**Comment by travisdowns** [comment] 2024-06-10 15:24
> @travisdowns Just flatpak as this is the flatpak repo. Native installs don't have this issue. See [#445 (comment)](https://github.com/flathub/us.zoom.Zoom/issues/445#issuecomment-2034301302) for the explanation.

Thanks, I hadn't noticed this was flatpak. I do have the same (user visible) issue but yeah this obviously isn't the right place to discuss it.

**Comment by bfahrenfort** [comment] 2024-09-03 03:58
I know this thread is mostly dead, but off of @rkaminsk 's solution, I tried forcing Firefox to open `zoommtg` linkx with `/usr/bin/zoom` (natively installed, will be different with Flatpak) and it fixed the issue.

**Comment by majneb** [comment] 2024-10-08 16:46
For me, it appeared that my custom .desktop file located in ./local/share/applications (that I use in KDE to run zoom with QT_AUTO_SCREEN_SCALE_FACTOR=1 environment variable) , did not have the proper Mime-type, and as a consequence firefox did not recognize the application. MimeType line in the .desktop file should contain `x-scheme-handler/zoommtg`. Then to be sure that the system takes this into account, run `update-desktop-database`.

**Comment by oryband** [comment] 2025-08-01 20:12
I can confirm. Please reopen

**Comment by siddhpant** [comment] 2025-08-02 11:16
If it happens, it would be a different "issue" as the problem causing the report has been fixed. So make a new one.
