### ISSUE TITLE
Scaling Issues in this week's update

### ISSUE THREAD

**Issue by emtes** [flathub/us.zoom.Zoom#204] opened 2020-09-16 18:11 UTC
I have a high definition display (1920x1200) and Zoom looks massive. Just last week it scaled perfectly. It used to be massive 2-3 months ago and was fixed.

Running GNOME, Wayland, POP_OS. Hope this helps!

**Comment by juliengs** [comment] 2020-09-18 05:03
Got the same issue as well. As a quickfix, I'm able to launch Zoom in a terminal with perfect scaling using the following workaround:
`QT_SCREEN_SCALE_FACTORS=.5 flatpak run us.zoom.Zoom`

For some reason, the autoScale parameter is ignored in the latest version (~/.var/app/us.zoom.Zoom/config/zoomus.conf).

**Comment by ememoho** [comment] 2020-09-18 10:11
Can confirm that the `autoScale=false` [option](https://github.com/flathub/us.zoom.Zoom/issues/190#issuecomment-648826734) no longer has an effect (on 5.2.458699.0906).

Expanding the quickfix above to override Zoom's env via flatpak currently works for me:
```bash
flatpak override --env=QT_SCREEN_SCALE_FACTORS=.5 us.zoom.Zoom
```

**Comment by 3ernhard** [comment] 2020-09-20 17:07
This seems also to be an issue for the rpm version.
Setting `useSystemTheme=true` in `~/.config/zoomus.conf` however fixes it, but sadly this doesn't work for the flatpak version.
It also only effects my laptop's monitor.

**Comment by danilkhromov** [comment] 2020-09-21 19:20
Im having the same issue.
Since last update zoom has something like 200% scaling of all interface elements on my laptop screen.
Setting `autoScale=false` or `useSystemTheme=true` has no effect.

**Comment by Galzzly** [comment] 2020-09-22 08:24
I had the same issue after the update last week, and resolved by updating Exec line in the file `~/.local/share/flatpak/exports/share/applications/us.zoom.Zoom.desktop` to include the `QT_SCREEN_SCALE_FACTORS` setting:

`Exec=env QT_SCREEN_SCALE_FACTORS=.5 /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=zoom --file-forwarding us.zoom.Zoom @@u %U @@`

This morning I updated to version `5.3.465578.0920` which undid the above setting, and set scaling to 200% on my laptop screen.

The above edit to the Exec line resolved again.

**Comment by sriv** [comment] 2020-09-22 14:38
I can see that `autoScale=false` is not honoured from either locations:

- `~/.config/zoomus.conf`
- `~/.var/app/us.zoom.Zoom/config/zoomus.conf`

I see this regression post merge of #199. I verified this by running `flatpak remote-info --log flathub us.zoom.Zoom` and then

`flatpak update --commit=e2fd6260c7527235fc242f9d58ffe3213e6c7c3ccae3ff9397ac7e26e29a021c us.zoom.Zoom` - auto scale works as expected.

`70eb533780462e3368458e9c169f68d7ec5640e7008b00f446a0f3461141f9ff` includes the change for #199, and I see the scaling broken (I guess this is because the conf isn't honoured)

**Comment by heftig** [comment] 2020-09-24 17:33
Zoom loads the scale settings from a file named `~/.config/zoomus.conf`, without regard for `XDG_CONFIG_HOME`. This seems to be some hack they added, since any other use of that file does follow the XDG spec. The recent changes to the sandbox broke this.

To fix this, you can:
1. Create a symlink `~/.var/app/us.zoom.Zoom/.config/zoomus.conf` → `~/.var/app/us.zoom.Zoom/config/zoomus.conf` (the target must be absolute) and
2. Run `flatpak override --persist=.config us.zoom.Zoom` to make this directory visible to Zoom.

Not sure how to best solve this when building the flatpak. Maybe a wrapper script that initializes the sandbox homedir with a `ln -s "$XDG_CONFIG_HOME" .config`.

**Comment by deisi** [comment] 2020-09-25 08:00
@heftig  solution works, but I had to run `flatpak override --persist=.config us.zoom.Zoom` as root.

**Comment by TheEvilSkeleton** [comment] 2020-09-26 14:39
> Zoom loads the scale settings from a file named `~/.config/zoomus.conf`, without regard for `XDG_CONFIG_HOME`. This seems to be some hack they added, since any other use of that file does follow the XDG spec. The recent changes to the sandbox broke this.
> 
> To fix this, you can:
> 
>     1. Create a symlink `~/.var/app/us.zoom.Zoom/.config/zoomus.conf` → `~/.var/app/us.zoom.Zoom/config/zoomus.conf` (the target must be absolute) and
> 
>     2. Make the settings changes to the latter file and
> 
>     3. Run `flatpak override --persist=.config us.zoom.Zoom` to make this directory visible to Zoom.
> 
> 
> Not sure how to best solve this when building the flatpak. Maybe a wrapper script that initializes the sandbox homedir with a `ln -Ts "$XDG_CONFIG_HOME" .config`.

Not sure, have you tried only doing step 3, while ignoring steps 2 and 1? I *might* get it to work if step 3 fixes the issue.

**Comment by heftig** [comment] 2020-09-26 15:32
No, the persist alone is definitely not enough. Zoom only tries to read this path, it doesn't write it.

**Comment by heftig** [comment] 2020-09-26 15:36
> Not really a hack, but we

I didn't mean you. I mean the Zoom authors added code that reads from `.config` without any regard for Qt's existing adherence to the XDG sir spec.

**Comment by TheEvilSkeleton** [comment] 2020-09-26 15:51
> > Not really a hack, but we
> 
> I didn't mean you. I mean the Zoom authors added code that reads from `.config` without any regard for Qt's existing adherence to the XDG dir spec.

I see. What do you think about giving read-write access to `~/.config/zoomus.conf`?

**Comment by TheEvilSkeleton** [comment] 2020-09-26 15:53
> > Not really a hack, but we
> 
> I didn't mean you. I mean the Zoom authors added code that reads from `.config` without any regard for Qt's existing adherence to the XDG dir spec.

I see, that sucks. I'll try to make it work

**Comment by heftig** [comment] 2020-09-26 16:13
> Unfortunately I don't really have anyone to test this with and I use a 1080p display, so I cannot be a tester. I will need some help

You could set `autoScale=false` and `scaleFactor=2` in `~/.var/app/us.zoom.Zoom/config/zoomus.conf` and then try your fixes. When Zoom starts with the windows way too large, you'll know it has read the settings.

**Comment by heftig** [comment] 2020-09-26 16:19
> Maybe a wrapper script that initializes the sandbox homedir with a ln -Ts "$XDG_CONFIG_HOME" .config.

To be clear, what I mean with this is that you wrap a shell script around the Zoom executable that creates the symlink before starting Zoom. This requires that `.config` is **not** persisted. AFAIU the sandbox always starts with an empty homedir, so creating the symlink should then always succeed.

**Comment by TheEvilSkeleton** [comment] 2020-09-26 17:32
Oh my god, I think I got it working. Everyone please test and confirm it for me if it works or not: https://github.com/flathub/us.zoom.Zoom/pull/212#issuecomment-699524524

**Comment by topas-rec** [comment] 2020-09-27 18:27
> Oh my god, I think we got it working. Everyone please test and confirm it for me if it works or not: [#212 (comment)](https://github.com/flathub/us.zoom.Zoom/pull/212#issuecomment-699529623)

Fixes the issue for me.

**Comment by danilkhromov** [comment] 2020-09-28 15:51
> Oh my god, I think we got it working. Everyone please test and confirm it for me if it works or not: [#212 (comment)](https://github.com/flathub/us.zoom.Zoom/pull/212#issuecomment-699529623)

Seems that it fixes issue for me as well.
But im wondering will the next update overwrite this fix or will it be included into it?

**Closed** 2020-09-28 18:21 UTC

**Comment by TheEvilSkeleton** [comment] 2020-09-28 18:47
>  But im wondering will the next update overwrite this fix or will it be included into it?

That's a good question. I don't know to be honest

**Comment by HarlemSquirrel** [comment] 2020-09-30 16:29
Setting `useSystemTheme=true` in ~/.config/zoomus.conf fixed this for me after updating to the latest flatpak in Fedora 32.

**Comment by biji** [comment] 2020-10-19 17:10
This work for me, run this from your home directory:
`touch .var/app/us.zoom.Zoom/.config/zoomus.conf`

Note the dot config and yes, blank file

**Comment by 1player** [comment] 2021-11-13 14:11
Please reopen this, scaling is broken yet again.

Works for me if I run `flatpak override --user --env=QT_SCALE_FACTOR=0.50 us.zoom.Zoom`

Changing the configuration file (disabling autoScale, or enabling useSystemTheme) at `~/.var/app/us.zoom.Zoom/config/zoomus.conf` doesn't do anything.

**Comment by ivoanjo** [comment] 2022-10-31 21:02
Still seeing this on 5.12.2 (4816), when run in desktop mode on a Steam Deck. The solution by 1player above fixes it.

**Comment by o-kotb** [comment] 2023-01-28 16:44
The latest zoom update fixed the scaling issues for me without needing workarounds. It was very noticeable when zoom was infinitely small with `QT_SCALE_FACTOR=0.001953125` (it used to be infinitely big without it). It now looks normal without any envs.

**Comment by hickscorp** [comment] 2024-03-06 14:06
@ememoho Amazing answer - not just for Zoom but more generally to allow tweaking Flatpak environments. Thanks a milion for this one.
