### ISSUE TITLE
zoom crashes since latest update

### ISSUE THREAD

**Issue by marco44** [flathub/us.zoom.Zoom#350] opened 2022-09-14 10:00 UTC
Reverting to ba3b018bc340be3260c49cd2fd0cb6e7d3a34810135d5818d085574c59ff0408 fixes the issue
I'm using latest kde, with wayland, on archlinux

No idea how to get a backtrack on a flatpak package, if there is a walkthrough somewhere, I can provide the result.

**Comment by trekistheway** [comment] 2022-09-14 19:09
I can confirm:
```
[Wed Sep 14 21:00:57 2022] QSGRenderThread[29100]: segfault at 0 ip 00007f002c091843 sp 00007eff60ff9360 error 4 in libwayland-client.so.0.20.0[7f002c090000+7000]
[Wed Sep 14 21:00:57 2022] Code: 0f 29 55 80 0f 29 5d 90 0f 29 65 a0 0f 29 6d b0 0f 29 75 c0 0f 29 7d d0 64 48 8b 04 25 28 00 00 00 48 89 85 28 ff ff ff 31 c0 <49> 8b 14 24 48 8d 45 10 4c 8d b5 80 fe ff ff 48 89 85 70 fe ff ff
[Wed Sep 14 21:02:50 2022] QSGRenderThread[30991]: segfault at 0 ip 00007fd61864e843 sp 00007fd552ffc360 error 4 in libwayland-client.so.0.20.0[7fd61864d000+7000]
[Wed Sep 14 21:02:50 2022] Code: 0f 29 55 80 0f 29 5d 90 0f 29 65 a0 0f 29 6d b0 0f 29 75 c0 0f 29 7d d0 64 48 8b 04 25 28 00 00 00 48 89 85 28 ff ff ff 31 c0 <49> 8b 14 24 48 8d 45 10 4c 8d b5 80 fe ff ff 48 89 85 70 fe ff ff
```

**Comment by mke1976** [comment] 2022-09-17 08:07
I'm also observing the crash when joining a call.

Fedora 36 and 37, KDE, Wayland

**Comment by jesse-osiecki** [comment] 2022-10-03 18:59
I had this issue in Pop! Os 22.04 until I installed `xdg-desktop-portal-wlr_0.6.0-1` (as part of an unrelated effort to fix screensharing). This seems to have eliminated the problem for myself though I do not know why

**Comment by infra-monkey** [comment] 2022-10-18 06:12
Same on Fedora 36/37 KDE Wayland
Had to revert to the rpm installation and set `noSandbox=true`
Otherwise the app systematically crashes when joining a meeting.
Screensharing is not allowed unless running on gnome.

Any information if the developpers are working on fixing this issue? Flatpak is meant to make development distro and DE agnostic after all.
@jesse-osiecki can you develop a bit what you got fixed with xdg wlr?

**Comment by papadop** [comment] 2022-10-26 09:19
Same here with the rpm zoom-5.12.2.4816-1.x86_64 fedora36/Xorg/cinnamon. The Log ends up with 

```
zoom started.
[CZPClientLogMgr::LogClientEnvironment] [MacAddr: FC:77:74:22:EA:52][client: Linux][OS:  Fedora Linux 36 Thirty Six x64][Hardware: CPU Core:6 Frenquency:2.6 G Memory size:31761MB CPU Brand:Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz GPU Brand:][Req ID: ]
Linux Client Version is 5.12.2 (4816)
QSG_RENDER_LOOP is 
XDG_CURRENT_DESKTOP = X-Cinnamon;   GDMSESSION = cinnamon;   XDG_SESSION_TYPE = x11
Graphics Card Info:: 00:02.0 VGA compatible controller: Intel Corporation CoffeeLake-H GT2 [UHD Graphics 630]
Zoom package arch is 64bit, runing OS arch is x86_64
qt.network.ssl: QSslSocket: cannot resolve EVP_PKEY_base_id
qt.network.ssl: QSslSocket: cannot resolve SSL_get_peer_certificate
qt.scenegraph.general: threaded render loop
qt.scenegraph.general: Using sg animation driver
qt.scenegraph.general: Animation Driver: using vsync: 16.67 ms
No PulseAudio daemon running, or not running as session daemon.
zoom was exited due to a handled signal: 11 
ZoomLauncher exit.
```

**Comment by euclip** [comment] 2022-12-19 08:48
I'm experiencing a problem where the Zoom flatpak version 5.12.9.367 crashes almost immediately after launching under a Gnome Wayland session in Fedora 37 Workstation. Zoom's windows will freeze up, and then Gnome will say the program isn't responding and I have to force quit Zoom.

Two things stand out in the stderr output: 1) the fact that Zoom is looking for pacmd but can't find it (could the crash be related to Fedora using Pipewire?) and 2) the line that says `libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)` (possibly an incompatibility with AMDGPU?).

<details>

<summary>Stderr output</summary>

```
ZoomLauncher started.
Zoom path is: /app/extra/zoom
cmd line: 
Start subprocess: /app/extra/zoom/zoom sucessfully,  process pid: 4 
Can't load/home/<snip>/.config/zoomus.conf
[4 zypak-helper] Wait found events, but sd-event found none
sh: line 1: pacmd: command not found
[14 preload-host-spawn-strategy] Warning: waitpid override ignores groups
[14 preload-host-spawn-strategy] Warning: waitpid override ignores groups
[14 preload-host-spawn-strategy] Warning: waitpid override ignores groups
                             Class      App      Lib Possible Culprit Flags
                resip::Connection      648      648 
                      resip::Data       36       36 
                 resip::DnsResult     1080     1080 
                   resip::Headers        1        1 
          resip::MsgHeaderScanner       40       40 
                resip::SipMessage     5208     5208 
         resip::TransportSelector      864      864 
                     resip::Tuple      128      128 
              resip::UdpTransport     1144     1144 
          resip::GenericIPAddress       28       28 

zoom started.
sh: line 1: pacmd: command not found
                             Class      App      Lib Possible Culprit Flags
                resip::Connection      648      648 
                      resip::Data       36       36 
                 resip::DnsResult     1080     1080 
                   resip::Headers        1        1 
          resip::MsgHeaderScanner       40       40 
                resip::SipMessage     5208     5208 
         resip::TransportSelector      864      864 
                     resip::Tuple      128      128 
              resip::UdpTransport     1144     1144 
          resip::GenericIPAddress       28       28 

zoom started.
sh: line 1: pacmd: command not found
                             Class      App      Lib Possible Culprit Flags
                resip::Connection      648      648 
                      resip::Data       36       36 
                 resip::DnsResult     1080     1080 
                   resip::Headers        1        1 
          resip::MsgHeaderScanner       40       40 
                resip::SipMessage     5208     5208 
         resip::TransportSelector      864      864 
                     resip::Tuple      128      128 
              resip::UdpTransport     1144     1144 
          resip::GenericIPAddress       28       28 

zoom started.
Client: Breakpad is using Single Client Mode! client fd = -1
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
sh: line 1: pacmd: command not found
                             Class      App      Lib Possible Culprit Flags
                resip::Connection      648      648 
                      resip::Data       36       36 
                 resip::DnsResult     1080     1080 
                   resip::Headers        1        1 
          resip::MsgHeaderScanner       40       40 
                resip::SipMessage     5208     5208 
         resip::TransportSelector      864      864 
                     resip::Tuple      128      128 
              resip::UdpTransport     1144     1144 
          resip::GenericIPAddress       28       28 

zoom started.
[CZPClientLogMgr::LogClientEnvironment] [MacAddr: <snip>][client: Linux][OS:  Freedesktop.org SDK 22.08 Flatpak runtime x64][Hardware: CPU Core:8 Frenquency:3.556 G Memory size:32016MB CPU Brand:AMD Ryzen 7 5800X3D 8-Core Processor            GPU Brand:][Req ID: ]
Linux Client Version is 5.12.9 (367)
QSG_RENDER_LOOP is 
XDG_CURRENT_DESKTOP = GNOME;   GDMSESSION = gnome;   XDG_SESSION_TYPE = wayland
Graphics Card Info:: 0f:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] (rev c1)
Zoom package arch is 64bit, runing OS arch is x86_64
qt.scenegraph.general: threaded render loop
qt.scenegraph.general: Using sg animation driver
qt.scenegraph.general: Animation Driver: using vsync: 4.18 ms
qt.scenegraph.general: Using sg animation driver
qt.scenegraph.general: Animation Driver: using vsync: 4.18 ms
qt.scenegraph.general: texture atlas dimensions: 1024x512
qt.scenegraph.general: R/G/B/A Buffers:   8 8 8 8
qt.scenegraph.general: Depth Buffer:      24
qt.scenegraph.general: Stencil Buffer:    8
qt.scenegraph.general: Samples:           -1
qt.scenegraph.general: GL_VENDOR:         AMD
qt.scenegraph.general: GL_RENDERER:       AMD Radeon RX 6800 XT (navi21, LLVM 14.0.6, DRM 3.48, 6.0.12-300.fc37.x86_64)
qt.scenegraph.general: GL_VERSION:        4.6 (Compatibility Profile) Mesa 22.2.4 (git-80df10f902)
qt.scenegraph.general: GL_EXTENSIONS:    GL_AMD_conservative_depth GL_AMD_depth_clamp_separate GL_AMD_draw_buffers_blend GL_AMD_framebuffer_multisample_advanced GL_AMD_multi_draw_indirect GL_AMD_performance_monitor GL_AMD_pinned_memory GL_AMD_query_buffer_object GL_AMD_seamless_cubemap_per_texture GL_AMD_shader_stencil_export GL_AMD_shader_trinary_minmax GL_AMD_texture_texture4 GL_AMD_vertex_shader_layer GL_AMD_vertex_shader_viewport_index GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_APPLE_packed_pixels GL_ARB_ES2_compatibility GL_ARB_ES3_1_compatibility GL_ARB_ES3_2_compatibility GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_bindless_texture GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_color_buffer_float GL_ARB_compatibility GL_ARB_compressed_texture_pixel_storage GL_ARB_compute_shader GL_ARB_compute_variable_group_size GL_ARB_conditional_render_inverted GL_ARB_conservative_depth GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_draw_indirect GL_ARB_draw_instanced GL_ARB_enhanced_layouts GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_gl_spirv GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader_int64 GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_indirect_parameters GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multi_draw_indirect GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_occlusion_query2 GL_ARB_parallel_shader_compile GL_ARB_pipeline_statistics_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_polygon_offset_clamp GL_ARB_post_depth_coverage GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_query_buffer_object GL_ARB_robust_buffer_access_behavior GL_ARB_robustness GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture GL_ARB_separate_shader_objects GL_ARB_shader_atomic_counter_ops GL_ARB_shader_atomic_counters GL_ARB_shader_ballot GL_ARB_shader_bit_encoding GL_ARB_shader_clock GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shader_image_load_store GL_ARB_shader_image_size GL_ARB_shader_objects GL_ARB_shader_precision GL_ARB_shader_stencil_export GL_ARB_shader_storage_buffer_object GL_ARB_shader_subroutine GL_ARB_shader_texture_image_samples GL_ARB_shader_texture_lod GL_ARB_shader_viewport_layer_array GL_ARB_shading_language_100 GL_ARB_shading_language_420pack GL_ARB_shading_language_include GL_ARB_shading_language_packing GL_ARB_shadow GL_ARB_sparse_buffer GL_ARB_sparse_texture GL_ARB_sparse_texture2 GL_ARB_sparse_texture_clamp GL_ARB_spirv_extensions GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_tessellation_shader GL_ARB_texture_barrier GL_ARB_texture_border_clamp GL_ARB_texture_buffer_object GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_buffer_range GL_ARB_texture_compression GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_cube_map_array GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_filter_anisotropic GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_mirrored_repeat GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_texture_view GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced GL_ARB_transform_feedback_overflow_query GL_ARB_transpose_matrix GL_ARB_uniform_buffer_object GL_ARB_vertex_array_bgra GL_ARB_vertex_array_object GL_ARB_vertex_attrib_64bit GL_ARB_vertex_attrib_binding GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_ARB_window_pos GL_ATI_blend_equation_separate GL_ATI_draw_buffers GL_ATI_fragment_shader GL_ATI_meminfo GL_ATI_separate_stencil GL_ATI_texture_compression_3dc GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_ATI_texture_mirror_once GL_EXT_EGL_image_storage GL_EXT_EGL_sync GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_compiled_vertex_array GL_EXT_copy_texture GL_EXT_demote_to_helper_invocation GL_EXT_depth_bounds_test GL_EXT_direct_state_access GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_memory_object GL_EXT_memory_object_fd GL_EXT_multi_draw_arrays GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_packed_pixels GL_EXT_pixel_buffer_object GL_EXT_point_parameters GL_EXT_polygon_offset_clamp GL_EXT_provoking_vertex GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_semaphore GL_EXT_semaphore_fd GL_EXT_separate_specular_color GL_EXT_shader_image_load_formatted GL_EXT_shader_image_load_store GL_EXT_shader_integer_mix GL_EXT_shader_samples_identical GL_EXT_shadow_funcs GL_EXT_stencil_two_side GL_EXT_stencil_wrap GL_EXT_subtexture GL_EXT_texture GL_EXT_texture3D GL_EXT_texture_array GL_EXT_texture_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_latc GL_EXT_texture_compression_rgtc GL_EXT_texture_compression_s3tc GL_EXT_texture_cube_map GL_EXT_texture_edge_clamp GL_EXT_texture_env_add GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_lod_bias GL_EXT_texture_mirror_clamp GL_EXT_texture_object GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_RG8 GL_EXT_texture_sRGB_decode GL_EXT_texture_shadow_lod GL_EXT_texture_shared_exponent GL_EXT_texture_snorm GL_EXT_texture_swizzle GL_EXT_timer_query GL_EXT_transform_feedback GL_EXT_vertex_array GL_EXT_vertex_array_bgra GL_EXT_vertex_attrib_64bit GL_EXT_window_rectangles GL_IBM_multimode_draw_arrays GL_IBM_rasterpos_clip GL_IBM_texture_mirrored_repeat GL_INGR_blend_func_separate GL_INTEL_blackhole_render GL_KHR_blend_equation_advanced GL_KHR_context_flush_control GL_KHR_debug GL_KHR_no_error GL_KHR_parallel_shader_compile GL_KHR_robust_buffer_access_behavior GL_KHR_robustness GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_sliced_3d GL_MESA_framebuffer_flip_y GL_MESA_pack_invert GL_MESA_shader_integer_functions GL_MESA_texture_signed_rgba GL_MESA_window_pos GL_NVX_gpu_memory_info GL_NV_alpha_to_coverage_dither_control GL_NV_blend_square GL_NV_compute_shader_derivatives GL_NV_conditional_render GL_NV_copy_depth_to_color GL_NV_copy_image GL_NV_depth_clamp GL_NV_fog_distance GL_NV_half_float GL_NV_light_max_exponent GL_NV_packed_depth_stencil GL_NV_primitive_restart GL_NV_shader_atomic_int64 GL_NV_texgen_reflection GL_NV_texture_barrier GL_NV_texture_env_combine4 GL_NV_texture_rectangle GL_NV_vdpau_interop GL_OES_EGL_image GL_OES_read_format GL_S3_s3tc GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_SUN_multi_draw_arrays
qt.scenegraph.general: Max Texture Size: 16384
qt.scenegraph.general: Debug context:    false
qt.scenegraph.general: animation driver switched to timer mode
qt.scenegraph.general: Using sg animation driver
qt.scenegraph.general: Animation Driver: using vsync: 4.18 ms
qt.scenegraph.general: texture atlas dimensions: 512x1024
qt.scenegraph.general: Using sg animation driver
qt.scenegraph.general: animation driver switched to vsync mode
zoom was exited due to a handled signal: 9 
ZoomLauncher exit.
```

</details>

**Comment by srsgores** [comment] 2022-12-19 21:11
Yeah, I had the same problem with the flatpak version on Manjaro.  Updated to the aur and now it works again.

**Comment by drodden-xevo** [comment] 2023-01-03 19:45
Linux Mint 21.1 Cinnamon edition here, and Cinnamon is gnome-based, I installed Zoom via Software Manager and it grabbed 5.12.9.367 from Flathub. Upon initially loading Zoom, the client crashes and I get asked to send an error report. But then I find zoom is still loaded, but no longer logged into my zoom account. It appears somewhat related to whether or not you logged into your account first or not. If I stay logged out of my zoom account in the client, I can close it and load it and it'll only crash 50% of the time on startup. If I log into my Zoom account and then close Zoom and re-open it, then it's pretty much 100% going to crash on startup.

**Comment by paithan** [comment] 2023-01-17 18:17
I am also experiencing problems with Zoom.  (Ubuntu 20.04 with KDE.)  It was working as recently as last week (Jan. 10).  The behavior I experienced today is: Browse to the URL -> Zoom begins to load -> Meeting host lets me in -> I am on the call for a fraction of a second, when it crashes.  To the other meeting participants, it appears that I am still there.
dmesg reports a segfault:
zoom[3369]: segfault at 10000018 ip 00007f5de307e3ce sp 00007fff4a977298 error 4 in libQt5Core.so.5.12.10[7f5de2de0000+589000]
When I try a second time, Zoom recognizes that there's an issue.  If I try to type this feedback there, however, the feedback window closes when it crashes again.
I was able to get into the meeting on my phone.

**Comment by andrey-gava** [comment] 2023-02-08 08:39
Have similar problem on Debian 11 (xfce) like @paithan described.
Zoom Version: 5.13.5 (431)
```
Feb  8 10:02:40 acer kernel: [ 2057.838650] zoom[3973]: segfault at 0 ip 0000000000000000 sp 00007ffea804a5c8 error 14 in zoom[55929c200000+8dec000]
Feb  8 10:02:40 acer kernel: [ 2057.838659] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
Feb  8 10:02:58 acer kernel: [ 2075.435237] zoom[4399]: segfault at 30 ip 0000000000000030 sp 00007ffe002a65f8 error 14 in zoom[55ee15c00000+8dec000]
Feb  8 10:02:58 acer kernel: [ 2075.435250] Code: Unable to access opcode bytes at RIP 0x6.
```

**Comment by violetmage** [comment] 2023-03-02 02:55
In my (uninformed) opinion, this seems to be more of a zoom issue (something for the zoom developers to fix), rather than a flatpak issue (something *we* can fix).

My reasoning for this opinion is that when using other flatpaks that perform similar functions to zoom (i.e. opening a zoom meeting in the chromium flatpak), none of these issues seem to exist.

**Comment by muelli** [comment] 2023-03-02 10:33
Thanks for the triaging @violetmage !

**Comment by muelli** [comment] 2023-03-02 10:33
Thanks for the triaging @violetmage!

**Closed by muelli** 2023-03-02 10:33 UTC

**Comment by Crypto-Sai** [comment] 2023-06-05 09:36
Just experienced the same :c

**Comment by loreno-heer** [comment] 2023-07-17 09:39
this issue re-appeared since the latest update

**Comment by James-Oakley** [comment] 2023-07-27 13:03
> this issue re-appeared since the latest update

+1

**Comment by hacker1024** [comment] 2023-08-07 07:33
I have worked around the issue by clicking the sidebar icon to hide the sidebar before it finishes loading, which causes the crash. This took a few tries - it's very fast.

**Comment by homes2001** [comment] 2023-08-08 10:02
@hacker1024 for me it loaded (crashed) too quick, however, i was able to use the workaround mentioned here: https://aur.archlinux.org/packages/zoom

> I found a workaround for this issue start zoom with QT_QPA_PLATFORM=xcb, and toggle off sidebar. after that you can run zoom with QT_QPA_PLATFORM=wayland and it will not crash untill you toggle the sidebar back 😃

**Comment by Kricken70** [comment] 2023-09-29 07:59
I found a workaround for the sidebar issue. Set disableCef=true in zoomus.conf

**Comment by James-Oakley** [comment] 2023-09-29 08:12
> I found a workaround for the sidebar issue. Set disableCef=true in zoomus.conf Works for me, Debian Sid

Thanks, that gets around the need to find a way to disable the sidebar manually. Doing that was itself a work-around to stop the Zoom app crashing. Some people had found disabling the sidebar fixed the crash. Sadly, without the sidebars (using disableCef), the app still crashes when I join a meeting. It now doesn't close instantly, instead the app freezes with the output from my camera frozen on screen, then shuts a few seconds later.
