### ISSUE TITLE
Video output fails when using backgrounds

### ISSUE THREAD

**Issue by NedCooleyFSA** [flathub/us.zoom.Zoom#330] opened 2022-05-09 15:18 UTC
## Error
Since the commit from 05-04 if the user selects the blurred background video will only output a black screen, if the user selects a background image then the video output freezes in place. Output with no background works normally.

## Workaround
Reverting to the commit from 04-29 got backgrounds working again.

## Details
OS: Pop!_OS 21.10
Flatpak version 1.11.2
Zoom version 5.10.4(2845) after workaround applied

**Comment by bertogg** [comment] 2022-05-10 10:48
I confirm this bug. Unfortunately 04-29 is not an option for me either because it doesn't work if you click on a Zoom meeting link from e.g. a web page. I have to revert to 03-22 (commit 972052877d97e307ba6ef722172d742331ef9f4dc868a31af8b7906d1f644237) in order to have meetings normally.

**Comment by hookenz** [comment] 2022-05-11 21:16
happens to me as well.  Blur causes the video to be frozen (not black)

**Comment by liskin** [comment] 2022-05-12 11:09
Happened to me as well with 5.10.6 (2022-05-09, flathub commit e7ce9d33dc81adb34d0e298d5f652bbeecafff0060231a35b185c0c2282d11f7), but it magically fixed itself after downgrading to 5.10.4 (2022-05-04, flathub commit 3da01de02976723cc6e5a1aed2231cfe271fd8481d38aa4cd2fc30d5912e2a33), disabling blue, upgrading again, and probably doing some other random steps in between. Seems to be this is just Zoom being Zoom? :-/

**Comment by jbiel** [comment] 2022-05-12 21:54
Same here. Zoom's client is my #1 annoyance with my computer at this point.

**Comment by hasrthur** [comment] 2022-05-14 21:44
In my case it's very strange. If I have blurred background setup and try to launch the meeting via the link in the browser I will have a black screen and if I disable it inside the meeting the video will work (in this case the client is not logged in for some reason), If I open zoom beforehand (and I am logged in) and then click the link, I will have the working blurred video. 
I am using zoom from flathub v 5.10.6.2943 and Fedora 36 Silverblue

**Comment by ieugen** [comment] 2022-05-18 15:20
I can confirm this on Debian 12 (testing) . 
Latest zoom available on flatpak  5.10.6 (2943) .

**Comment by hasrthur** [comment] 2022-05-18 15:29
Hm, I have just tested and in my case zoom freezes when I connect my bluetooth headphones using high fidelity audio. If I switch mono unit (or whatever it is called in gnome settings) zoom freezes when I try to join the meeting or when trying to go to Audio settings. But there are moment when everything works ok so I don't have 100% way to reproduce the issue

**Comment by helohe** [comment] 2022-06-21 11:05
According to the changelog this is fixed in 5.10.7. Can someone update the flatpak?

**Comment by liskin** [comment] 2022-06-21 11:59
> According to the changelog this is fixed in 5.10.7. Can someone update the flatpak?

https://github.com/flathub/us.zoom.Zoom/pull/335 and https://github.com/flathub/us.zoom.Zoom/pull/336 (no idea why two of them) were created automatically and include instructions for testing the build, so you can try that and report back whether it's fixed by the update.

**Comment by helohe** [comment] 2022-06-21 12:50
> > According to the changelog this is fixed in 5.10.7. Can someone update the flatpak?
> 
> #335 and #336 (no idea why two of them) were created automatically and include instructions for testing the build, so you can try that and report back whether it's fixed by the update.

Both of them return 404 for me when I try to install them.

**Comment by nedrichards** [comment] 2022-06-21 20:53
I've retriggered a build and will test and merge

**Comment by nedrichards** [comment] 2022-06-22 19:32
Before then 5.11 was released and is out, can you test again with that? Backgrounds appears to work for me with that.

**Comment by bertogg** [comment] 2022-06-22 20:26
I confirm that it works fine with 5.11.0.3540

**Comment by dtrunk90** [comment] 2022-06-23 10:18
Same here. But I'll give it some more days to test because it only happened randomly for me.

**Comment by dtrunk90** [comment] 2022-06-24 11:21
Yes, seems to work again. At least I've tried it in two meetings now each day.

**Comment by nedrichards** [comment] 2022-06-24 21:44
OK, I'll close for now. Feel free to open again if it occurs again but I doubt it'll be flatpak specific.

**Closed by nedrichards** 2022-06-24 21:44 UTC
