### ISSUE TITLE
Can't login with Google account

### ISSUE THREAD

**Issue by krashekspres** [flathub/us.zoom.Zoom#14] opened 2018-09-24 06:42 UTC
When I try to sign in with Google I'm getting an error as on attachment and then Zoom opens another browser and it does that indefinitely (as long as I'm pressing login button). 
![zoom_error](https://user-images.githubusercontent.com/20690019/45939811-93002680-bfd5-11e8-8ec1-e63f51f9b54b.png)

**Comment by chaseadam** [comment] 2018-10-09 18:57
I believe this is related to the google sign on (and likely any SSO option) response being sent to a new instance rather than the "original" instance. This issue is reported in #12

**Comment by rosstimson** [comment] 2019-07-15 15:22
Yeah, this was fixed with:  https://github.com/flathub/us.zoom.Zoom/pull/28/files

I think this issue can be closed.

**Closed** 2019-07-15 20:13 UTC

**Comment by pksol** [comment] 2019-11-12 08:59
This happened to me and several of my friends in the last two days. What to do?

**Comment by jdchristensen** [comment] 2020-01-24 17:39
I just created a fresh zoom account via my google account, and am not able to log into zoom using the zoom client.  I get redirected to the google confirmation page, then zoom is relaunched but sits there saying "Connecting to Google..."

I'm using version 2.8.252201.0616 which is supposed to contain a fix for this.

Reopen?

**Comment by jdchristensen** [comment] 2020-01-27 16:03
With a 3.5.something version, logging in via a google account works fine.

**Comment by janjwesselink** [comment] 2020-04-01 18:01
I am having this issue with the linux client, version 3.5.37... it just opens a new browser window

**Comment by antariess** [comment] 2020-04-20 15:45
has there been a solution or fix to this? been experiencing the same issue with multiple account ive created over the last week

**Comment by Ramly** [comment] 2020-04-22 14:33
Keep having this issue with both my personal and work accounts. Incredibly frustrating.

**Comment by vkbo** [comment] 2020-04-28 15:15
Same here. I always get "400. That’s an error. The requested URL was not found on this server. That’s all we know." from Google when I try to sign in from the app. Using Debian, and app version 5.0.398100.0427. Signing in on website works just fine.

**Comment by rsuhada-ampx** [comment] 2020-07-08 12:42
Still an issue in 5.1.418436.0628

**Comment by kiat-huang** [comment] 2020-07-08 16:59
I can not log in to my zoom.us account any more.  I am a Pro subscriber.

My account access is with my Google account which has worked for months, now, today the Google Auth is broken, not only from the client (Linux) but also natively on the website (zoom.us).

**Comment by SamReciter** [comment] 2020-07-09 13:02
Can't login with Google at zoom.us/signin - just redirects to same site with get params error=access_denied and some identifiers afterwords...

**Comment by pharaxe** [comment] 2020-07-11 17:25
This is happening to me as well, I see the error=access_denied parameter in the URL but I don't see any error messages in the UI.

**Comment by hkarlsson** [comment] 2020-07-12 00:38
> I can not log in to my zoom.us account any more. I am a Pro subscriber.
> 
> My account access is with my Google account which has worked for months, now, today the Google Auth is broken, not only from the client (Linux) but also natively on the website (zoom.us).

I have the same issue, when using Chrome but I can still login through Safari. Maybe that works for you too :)

**Comment by yuehengshi** [comment] 2020-07-12 14:31
The same issue has occurred since last week with Chrome and Safari. At first, I could login with on my MacBook and mac pro but not worked with windows. Now, I can't login with any devices.

**Comment by yuehengshi** [comment] 2020-07-12 23:26
Is anybody here? I wanted to report this issue to customer support, but it needs me to login...

**Comment by dkoontz** [comment] 2020-07-15 18:35
> I can not log in to my zoom.us account any more. I am a Pro subscriber.
> 
> My account access is with my Google account which has worked for months, now, today the Google Auth is broken, not only from the client (Linux) but also natively on the website (zoom.us).

I am having this exact same issue. Worked fine for a year then broke a few days ago.

**Comment by firstnevyn** [comment] 2020-07-18 02:41
fat client is wokring for me chrome to the website zoom.us isn't working for me

**Comment by mars64** [comment] 2020-08-05 20:00
Reproduced, again, with latest version: `5.2.0 (42634.0805)`

Open the thick client, click `Sign in with Google`, I choose the Google account that should have permission here, I get an error: 

```
Something went wrong
Sorry, something went wrong there. Try again.
```

I click `next`, and receive: 

```
400. That’s an error.

The server cannot process the request because it is malformed. It should not be retried. That’s all we know.
```

It works if I go to the zoom.us site to log in, but I cannot join a meeting from the links in my Calendar items.

**Comment by jedabero** [comment] 2020-08-08 17:29
To anyone finding this issue:

Try clearing cache or cookies

But if you're like me and don't want to do that:
- Open a guest session in your browser
- (Optional) Close all other browser windows
- Try the Sign in with Google button again, it should open a new window with the guest session
- Do your normal google sign in
- Ta da... hopefully

**Comment by omonk** [comment] 2020-08-25 10:36
> To anyone finding this issue:
> 
> Try clearing cache or cookies
> 
> But if you're like me and don't want to do that:
> 
> * Open a guest session in your browser
> * (Optional) Close all other browser windows
> * Try the Sign in with Google button again, it should open a new window with the guest session
> * Do your normal google sign in
> * Ta da... hopefully

Can confirm this worked for me! Thanks

**Comment by RicoTrevisan** [comment] 2020-09-28 15:11
Another idea to try: disable any ad blockers you might have. I have Privacy Badger and it was blocking something that Google needed in order to authenticate.

**Comment by alanna-casey** [comment] 2020-09-29 21:18
@RicoTrevisan thank you -- same config here, and that resolved my issues.

**Comment by alejandrofloresm** [comment] 2021-02-06 15:51
> Another idea to try: disable any ad blockers you might have. I have Privacy Badger and it was blocking something that Google needed in order to authenticate.

In case someone is wondering what to filter, as today I had to add to privacy badger:

accounts.google.com
play.google.com

**Comment by yozek1988** [comment] 2024-02-15 08:23
Solved by reinstalling Zoom from tar file downloaded from official site. 
[]https://zoom.us/download?os=linux(url)
instruction
[https://support.zoom.com/hc/en/article?id=zm_kb&sysparm_article=KB0063458](url)
Problem was with zoom that installing with command
flatpak install us.zoom.Zoom
[]https://software.manjaro.org/flatpak/us.zoom.Zoom(url)
